# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  - publications
  - news

# Template examples that are not used on this site
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - blog.html
  - showcase.html
  - index_layout2.html
  - _posts
  - _showcase
  - _publications/2023/2023-pub-example-1.md
  - _publications/2023/2023-pub-example-2.md
  - _publications/2023/2023-pub-example-no-cover.md
  - _publications/2024/2024-pub-example-3.md
  - _news/2022-lorem.md
  - _news/2023-news1.md
  - _news/2023-news2.md
  - _news/2024-news1.md
  - _news/2024-news2.md
  - _news/2024-news3.md
  - assets/images/etc
  - assets/images/covers
